/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>


/* Header for class com_github_sviengine_basetype_SVIImage */



#ifndef _Included_com_github_sviengine_basetype_SVIImage

#define _Included_com_github_sviengine_basetype_SVIImage

#ifdef __cplusplus

extern "C" {

#endif

/*

 * Class:     com_github_sviengine_basetype_SVIImage

 * Method:    nativeCreateSVIImage

 * Signature: ()I

 */

JNIEXPORT jint JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeCreateSVIImage

  (JNIEnv *, jclass);



/*

 * Class:     com_github_sviengine_basetype_SVIImage

 * Method:    nativeDeleteSVIImage

 * Signature: (I)V

 */

JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeDeleteSVIImage

  (JNIEnv *, jclass, jint, jint);



/*

 * Class:     com_github_sviengine_basetype_SVIImage

 * Method:    nativeLock

 * Signature: ()V

 */

JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeLock

  (JNIEnv *, jclass, jint);



/*

 * Class:     com_github_sviengine_basetype_SVIImage

 * Method:    nativeUnlock

 * Signature: ()V

 */

JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeUnlock

  (JNIEnv *, jclass, jint);


/*
 * Class:     com_github_sviengine_basetype_SVIImage
 * Method:    nativeSetEmpty
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeSetEmpty
    (JNIEnv *, jclass, jint);


/*
 * Class:     com_github_sviengine_basetype_SVIImage
 * Method:    nativeSetBitmap
 * Signature: (I, ILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeSetBitmap
  (JNIEnv *, jclass, jint,  jint, jobject);

/*
 * Class:     com_github_sviengine_basetype_SVIImage
 * Method:    nativeSetCopyBitmap
 * Signature: (I, ILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeSetCopyBitmap
  (JNIEnv *, jclass, jint, jobject);


/*
 * Class:     com_github_sviengine_basetype_SVIImage
 * Method:    nativeSetRawBufferDirect
 * Signature: (I, ILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeSetRawBufferDirect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray);

/*
* Class:     com_github_sviengine_basetype_SVIImage
* Method:    nativeSetTextureIdDirect
* Signature: (I, ILandroid/graphics/Bitmap;)V
*/
JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeSetTextureIdDirect
    (JNIEnv *, jclass, jint,   jint, jint, jint);


/*
 * Class:     com_github_sviengine_basetype_SVIImage
 * Method:    nativeSetBitmap_compress
 * Signature: (II[B)V
 */

JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeSetBitmapCompress
    (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_github_sviengine_basetype_SVIImage
 * Method:    nativeSetAlphaType
 * Signature: (I, I;)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_basetype_SVIImage_nativeSetAlphaType
  (JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus

}

#endif

#endif

