/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_animation_SVITransitionAnimation */

#ifndef _Included_com_github_sviengine_animation_SVITransitionAnimation
#define _Included_com_github_sviengine_animation_SVITransitionAnimation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_sviengine_animation_SVITransitionAnimation_MSG_EXPLICIT_ANIMATION_END
#define com_github_sviengine_animation_SVITransitionAnimation_MSG_EXPLICIT_ANIMATION_END 1L
#undef com_github_sviengine_animation_SVITransitionAnimation_MSG_EXPLICIT_ANIMATION_REPEAT
#define com_github_sviengine_animation_SVITransitionAnimation_MSG_EXPLICIT_ANIMATION_REPEAT 2L
#undef com_github_sviengine_animation_SVITransitionAnimation_MSG_EXPLICIT_ANIMATION_START
#define com_github_sviengine_animation_SVITransitionAnimation_MSG_EXPLICIT_ANIMATION_START 3L
/*
 * Class:     com_github_sviengine_animation_SVITransitionAnimation
 * Method:    nativeCreateSVITransitionAnimation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_animation_SVITransitionAnimation_nativeCreateSVITransitionAnimation__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_animation_SVITransitionAnimation
 * Method:    nativeSetDirectionTypeSVITransitionAnimation
 * Signature: (II)I
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVITransitionAnimation_nativeSetDirectionTypeSVITransitionAnimation
  (JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
