/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_particle_SVIKeyFrameParticleEffect */

#ifndef _Included_com_github_sviengine_particle_SVIKeyFrameParticleEffect
#define _Included_com_github_sviengine_particle_SVIKeyFrameParticleEffect
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_github_sviengine_particle_SVIKeyFrameParticleEffect_nativeCreateKeyFrameParticleEffect
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIKeyFrameParticleEffect_nativeAddParticles
  (JNIEnv *, jclass, jint, jfloat, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIKeyFrameParticleEffect_nativeSetGeneratorPositionKeyFrameAnimationProperty
  (JNIEnv *, jclass, jint, jint, jint, jint);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIKeyFrameParticleEffect_nativeAddGeneratorPositionKeyFrame
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);


#ifdef __cplusplus
}
#endif
#endif

