/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_animation_SVIAnimation */

#ifndef _Included_com_github_sviengine_animation_SVIAnimation
#define _Included_com_github_sviengine_animation_SVIAnimation
#ifdef __cplusplus
extern "C" {
#endif

void nativeImplicitOnAnimationEnd(unsigned int listenerID, unsigned int animation);
void nativeImplicitOnAnimationRepeat(unsigned int listenerID, unsigned int animation);
void nativeImplicitOnAnimationStart(unsigned int listenerID, unsigned int animation);
void nativeOnAnimationEnd(unsigned int listenerID, unsigned int animation);
void nativeOnAnimationRepeat(unsigned int listenerID, unsigned int animation);
void nativeOnAnimationStart(unsigned int listenerID, unsigned int animation);

/*
 * Class:     com_github_sviengine_animation_SVIAnimation
 * Method:    nativeSetInterpolatorSVIAnimation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimation_nativeSetInterpolatorSVIAnimation
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_animation_SVIAnimation
 * Method:    nativeSetAnimationPropertySVIAnimation
 * Signature: (IIIZI)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimation_nativeSetAnimationPropertySVIAnimation
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint);

/*
 * Class:     com_github_sviengine_animation_SVIAnimation
 * Method:    nativeSetListenerSVIAnimation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimation_nativeSetListenerSVIAnimation
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimation_nativeDeleteSVIAnimation
  (JNIEnv *env, jclass jobject, jint aniHandle, jint classType);

/*
 * Class:     com_github_sviengine_animation_SVIAnimation
 * Method:    nativeCreteProxySVIAnimation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_animation_SVIAnimation_nativeCreteProxySVIAnimation
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_animation_nativeDeleteProxySVIAnimation
 * Method:    nativeDeleteProxySVIAnimation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimation_nativeDeleteProxySVIAnimation
	(JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_animation_nativeDeleteProxySVIAnimation
 * Method:    nativeDeleteProxySVIAnimation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimation_nativeSetListenerID
	(JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus
}
#endif
#endif


