///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
///* Header for class com_github_sviengine_glexternalsurface_SVIGLExternalSurface */
//
//#ifndef _Included_com_github_sviengine_glexternalsurface_SVIGLExternalSurface
//#define _Included_com_github_sviengine_glexternalsurface_SVIGLExternalSurface
//#ifdef __cplusplus
//extern "C" {
//#endif
//#undef com_github_sviengine_glexternalsurface_SVIGLExternalSurface_DEBUG
//#define com_github_sviengine_glexternalsurface_SVIGLExternalSurface_DEBUG 1L
//
//void requestRenderGLExternalSurface();
//
///*
// * Class:     com_github_sviengine_glexternalsurface_SVIGLExternalSurface
// * Method:    nativeInitSVIGLExternalSurface
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeInitSVIGLExternalSurface
//  (JNIEnv *, jclass, jint, jint);
//
///*
// * Class:     com_github_sviengine_glexternalsurface_SVIGLExternalSurface
// * Method:    nativeResizeSVIGLExternalSurface
// * Signature: (II)V
// */
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeResizeSVIGLExternalSurface
//  (JNIEnv *, jclass, jint,  jint, jint, jint);
//
///*
// * Class:     com_github_sviengine_glexternalsurface_SVIGLExternalSurface
// * Method:    nativeRenderSVIGLExternalSurface
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeRenderSVIGLExternalSurface
//  (JNIEnv *, jclass, jint,  jint updateMsg);
//
///*
// * Class:     com_github_sviengine_glexternalsurface_SVIGLExternalSurface
// * Method:    nativeResumeSVIGLExternalSurface
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeResumeSVIGLExternalSurface
//  (JNIEnv *, jclass, jint);
//
///*
// * Class:     com_github_sviengine_glexternalsurface_SVIGLExternalSurface
// * Method:    nativePauseSVIGLExternalSurface
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativePauseSVIGLExternalSurface
//  (JNIEnv *, jclass, jint);
//
///*
// * Class:     com_github_sviengine_glexternalsurface_SVIGLExternalSurface
// * Method:    nativeSetAssetManager
// * Signature: (Landroid/content/res/AssetManager;)V
// */
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeSetAssetManager
//  (JNIEnv *, jclass, jint,  jobject);
//
//
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeSwapAnimationSVIGLExternalSurface
//	(JNIEnv *, jclass, jint);
//
///*
//JNIEXPORT void JNICALL Java_com_github_sviengine_unittest_PageTurnEffectWindow_nativeTouchEvent
//	(JNIEnv *, jclass, jint, jfloat, jfloat);
//
//*/
//
////2012-01-02 masterkeaton27@gmail.com
////display & log fps info.
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeEnableShowFPS
//	(JNIEnv *, jclass, jint,  jboolean);
//
//JNIEXPORT void JNICALL Java_com_github_sviengine_glexternalsurface_SVIGLExternalSurface_nativeEnableLogFPS
//	(JNIEnv *, jclass, jint,  jboolean);
//
//
//#ifdef __cplusplus
//}
//#endif
//#endif
//
