/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_animation_SVIKeyFrameAnimation */

#ifndef _Included_com_github_sviengine_animation_SVIKeyFrameAnimation
#define _Included_com_github_sviengine_animation_SVIKeyFrameAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_sviengine_animation_SVIKeyFrameAnimation
 * Method:    nativeCreateSVIKeyFrameAnimation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_animation_SVIKeyFrameAnimation_nativeCreateSVIKeyFrameAnimation
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_animation_SVIKeyFrameAnimation
 * Method:    nativeAddKeyProperty
 * Signature: (IIF[F)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIKeyFrameAnimation_nativeAddKeyProperty
  (JNIEnv *, jclass, jint, jint, jfloat, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
