/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_slide_SVISlide */

#ifndef _Included_com_github_sviengine_debug_SVIFTrace
#define _Included_com_github_sviengine_debug_SVIFTrace
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Java_com_github_sviengine_debug_SVIFTrace_nativeEnable
 * Method:    nativeSetRootSlideSVISlide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_debug_SVIFTrace_nativeEnable
  (JNIEnv *, jclass);

/*
 * Class:     Java_com_github_sviengine_debug_SVIFTrace_nativeDisable
 * Method:    nativeDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_debug_SVIFTrace_nativeDisable
  (JNIEnv *, jclass);

/*
 * Class:     Java_com_github_sviengine_debug_SVIFTrace_nativeMark
 * Method:    nativeMark
 * Signature: (jstring)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_debug_SVIFTrace_nativeMark
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif

