/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_animation_SVIAnimationSet */

#ifndef _Included_com_github_sviengine_animation_SVIAnimationSet
#define _Included_com_github_sviengine_animation_SVIAnimationSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_sviengine_animation_SVIAnimationSet
 * Method:    nativeCreateSVIAnimationSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_animation_SVIAnimationSet_nativeCreateSVIAnimationSet
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_animation_SVIAnimationSet
 * Method:    nativeShareAnimationInfo
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimationSet_nativeShareAnimationInfo
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_animation_SVIAnimationSet
 * Method:    nativeAddAnimationSVIAnimationSet
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_sviengine_animation_SVIAnimationSet_nativeAddAnimationSVIAnimationSet
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_animation_SVIAnimationSet
 * Method:    nativeRemoveAnimationSVIAnimationSet
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimationSet_nativeRemoveAnimationSVIAnimationSet
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_animation_SVIAnimationSet
 * Method:    nativeSetPropertySVIAnimationSet
 * Signature: (IIIZI)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIAnimationSet_nativeSetPropertySVIAnimationSet
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif

