/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../Utils/SVIMutex.h"
/* Header for class com_github_sviengine_slide_SVISlide */

#ifndef _Included_com_github_sviengine_slide_SVISlide
#define _Included_com_github_sviengine_slide_SVISlide
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_sviengine_slide_SVISlide_IMPLICIT_ANIMATION_OFF_DURATION
#define com_github_sviengine_slide_SVISlide_IMPLICIT_ANIMATION_OFF_DURATION 0L

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetRootSlideSVISlide for Multi-Instance
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetRootSlideSVISlide
  (JNIEnv *, jclass,  jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeDisplaySlideTreesSVISlide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeDisplaySlideTreesSVISlide
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    initializeSVISlide
 * Signature: (IIFFFF[FLandroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_slide_SVISlide_nativeInitializeSVISlide
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloatArray, jobject);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeDestroySVISlide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeDestroySVISlide
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeInitRegionSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeInitRegionSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeInitRotationSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeInitRotationSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeInitScaleSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeInitScaleSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeInitOpacitySVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeInitOpacitySVISlide
   (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeInitBackgroundColorSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeInitBackgroundColorSVISlide
   (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeInitZPositionSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeInitZPositionSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetRegionSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetRegionSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBoundsSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBoundsSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetPositionSVISlide
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetPositionSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetPivotPointSVISlide
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetPivotPointSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetZPositionSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetZPositionSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetRotationSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetRotationSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetSwipeRatioSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetSwipeRatioSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetDeformRatioSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetDeformRatioSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetRTERatioSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetRTERatioSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetScaleSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetScaleSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBackgroundColorSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBackgroundColorSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetOpacitySVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetOpacitySVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetCornerRadiusSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetCornerRadiusSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBorderWidthSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBorderWidthSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBorderColorSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBorderColorSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetShadowRadiusSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetShadowRadiusSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetShadowColorSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetShadowColorSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetShadowOpacitySVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetShadowOpacitySVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetShadowOffsetSVISlide
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetShadowOffsetSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightAngleSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightAngleSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightRadiusSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightRadiusSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightOpacitySVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightOpacitySVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightPowerSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightPowerSVISlide
  (JNIEnv *, jclass, jint, jfloat);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightOffsetSVISlide
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightOffsetSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightColorSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightColorSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightDirectionSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightDirectionSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetViewDirectionSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetViewDirectionSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetLightTypeSVISlide
	(JNIEnv *, jclass, jint, jint);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetLightTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetScaleToFitTypeSVISlide
	(JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetTextureRegionSVISlide
 * Signature: (IFFFF)V
 */

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetTextureScaleToFitRegionSVISlide
	(JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetTextureRegionSVISlide
 * Signature: (IFFFF)V
 */

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetTextureRegionSVISlide
	(JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetTextureRegionSVISlide
 * Signature: (IFFFF)V
 */

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBackFaceTextureRegionSVISlide
	(JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetRotationFromSVISlide
 * Signature: (IFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetRotationFromSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetHiddenSVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetHiddenSVISlide
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetZOrderTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetZOrderTypeSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetSwipeTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetSwipeTypeSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetDeformTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetDeformTypeSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetMorphingTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetMorphingTypeSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetMorphingRadiusSVISlide
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetMorphingRadiusSVISlide
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetMorphingGridCountSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetMorphingVertexCountSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetMorphingColorSVISlide
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetMorphingColorSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetFilterTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetFilterTypeSVISlide
  (JNIEnv *, jclass, jint, jint);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetDeformDirectionSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetDeformDirectionSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetClipSubSlidesSVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetClipSubSlidesSVISlide
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:   nativeSetOrthogonalSVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetOrthogonalSVISlide
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:   nativeSetUseNormalMapSVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetUseNormalMapSVISlide
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:   nativeSetCustomRTESVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetCustomRTESVISlide
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:   nativeSetHoldOpacitySVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetHoldOpacitySVISlide
  (JNIEnv *, jclass, jint, jboolean);

 /*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:   nativeSetHoldScaleSVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetHoldScaleSVISlide
  (JNIEnv *, jclass, jint, jboolean);


 /*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:   nativeSetCaptureSVISlide
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetCaptureSVISlide
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBlendTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBlendTypeSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetRTEffectTypeSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetRTEffectTypeSVISlide
  (JNIEnv *, jclass, jint, jint);

//2011.12.09 jongchae.moon
/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetAntiAliasing
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetAntiAliasing
  (JNIEnv *, jclass, jint, jboolean);
//

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeGetRegion
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_github_sviengine_slide_SVISlide_nativeGetRegionSVISlide
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    addSlideIndexSVISlide
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeAddSlideIndexSVISlide
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    addSlideSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeAddSlideSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    removeSlideSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeRemoveSlideSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    removeAllSlidesSVISlide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeRemoveAllSlidesSVISlide
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    removeSlideAtSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeRemoveSlideAtSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    removeSlidesSVISlide
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeRemoveSlidesSVISlide
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBitmapSVISlide
 * Signature: (ILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBitmapSVISlide
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetImageSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetImageSVISlide
  (JNIEnv *, jclass, jint, jint);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetNormalImageSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetNormalImageSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetSpecularImageSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetSpecularImageSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBackFaceImageSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBackFaceImageSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetTesselationPointListSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetTesselationPointListSVISlide
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetTesselationPointListSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetTesselationPointListSVISlide
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBackFaceImageFlipSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBackFaceImageFlipSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeSetBackFaceImageClearSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetBackFaceImageClearSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeStartAnimationSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeStartAnimationSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeStopAnimationSVISlide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeStopAnimationSVISlide
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeRunExplicitAnimationSVISlide
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeRunExplicitAnimationSVISlide
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetImplicitAnimationSVISlide
  	(JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetExplicitAnimationSVISlide
  	(JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetProxySVISlide
  	(JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeIsSlideAnimating
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_slide_SVISlide_nativeIsSlideAnimating
	(JNIEnv *, jclass, jint);
/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeAddPathPoint
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeAddPathPoint
	(JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_slide_SVISlide
 * Method:    nativeClearPathPoints
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeClearPathPoints
    (JNIEnv *, jclass, jint);


//below jni interfaces are need to be descripted.

JNIEXPORT jint JNICALL Java_com_github_sviengine_slide_SVISlide_nativeLoad3dModelFileSVISlide
  (JNIEnv *, jclass, jint, jstring);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeRemoveSceneNodeSVISlide
  (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetModelPositionSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetModelRotationSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeSetModelScaleSVISlide
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlide_nativeAddParticleEffectSVISlide
  (JNIEnv *, jclass, jint, jint);

/*
 * Mutex for synchronizing access to slide tree data.
 */
static SVI::SVIMutex*			mLockAddingSlides = new SVI::SVIMutex("Add slide lock");

#ifdef __cplusplus
}
#endif
#endif
