/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_posteffect_SVIPostEffectManager */

#ifndef _Included_com_github_sviengine_posteffect_SVIPostEffectManager
#define _Included_com_github_sviengine_posteffect_SVIPostEffectManager

#ifdef __cplusplus
extern "C" {
#endif


//2013-02-27 masterkeaton27@gmail.com
void nativeRippleFinishedCallback();


/*
 * Class:     com_github_sviengine_posteffect_SVIPostEffectManager
 * Method:    nativeResetRipple
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_posteffect_SVIPostEffectManager_nativeResetRipple
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_sviengine_posteffect_SVIPostEffectManager
 * Method:    nativeSetRipple
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_posteffect_SVIPostEffectManager_nativeSetRipple
  (JNIEnv *, jclass, jint,  jfloat, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_posteffect_SVIPostEffectManager
 * Method:    nativeSetRippleInfo
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_posteffect_SVIPostEffectManager_nativeSetRippleInfo
  (JNIEnv *, jclass, jint, jfloat, jfloat);


/*
 * Class:     com_github_sviengine_posteffect_SVIPostEffectManager
 * Method:    nativeSetRippleEnvImage
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_posteffect_SVIPostEffectManager_nativeSetRippleEnvImage
  (JNIEnv *, jclass, jint);


/*
 * Class:     com_github_sviengine_posteffect_SVIPostEffectManager
 * Method:    nativeEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_posteffect_SVIPostEffectManager_nativeEnable
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_posteffect_SVIPostEffectManager
 * Method:    nativeSetType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_posteffect_SVIPostEffectManager_nativeSetType
	(JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus
}
#endif

#endif



