/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_slide_SVISlideManager */

#ifndef _Included_com_github_sviengine_slide_SVISlideManager
#define _Included_com_github_sviengine_slide_SVISlideManager

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_github_sviengine_slide_SVISlideManager
 * Method:    nativeIsAnimatingSVISlideManager
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_slide_SVISlideManager_nativeIsAnimatingSVISlideManager
  (JNIEnv *, jclass, jint );

/*
 * Class:     com_github_sviengine_slide_SVISlideManager
 * Method:    nativeEnableGlobalAnimation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_slide_SVISlideManager_nativeEnableGlobalAnimation
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_slide_SVISlideManager
 * Method:    nativeIsEnableGlobalAnimation
 * Signature: (V)I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_slide_SVISlideManager_nativeIsEnableGlobalAnimation
	(JNIEnv *, jclass, jint );

/*
 * Class:     com_github_sviengine_slide_SVISlideManager
 * Method:    nativeGetFPS
 * Signature: (V)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_sviengine_slide_SVISlideManager_nativeGetFPS
	(JNIEnv *, jclass, jint );

/*
 * Class:     com_github_sviengine_slide_SVISlideManager
 * Method:    nativeCheckPageStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_slide_SVISlideManager_nativeCheckPageStatus
	(JNIEnv *, jclass,  jint);
#ifdef __cplusplus
}

#endif
#endif



