/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_animation_SVIBasicAnimation */

#ifndef _Included_com_github_sviengine_animation_SVIBasicAnimation
#define _Included_com_github_sviengine_animation_SVIBasicAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_sviengine_animation_SVIBasicAnimation
 * Method:    nativeCreateSVIBasicAnimation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_animation_SVIBasicAnimation_nativeCreateSVIBasicAnimation
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sviengine_animation_SVIBasicAnimation
 * Method:    nativeSetValueSVIBasicAnimation
 * Signature: (II[F[F)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIBasicAnimation_nativeSetValueSVIBasicAnimation
  (JNIEnv *, jclass, jint, jint, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif


