/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_slide_SVISlide */

#ifndef _Included_com_github_sviengine_animation_SVISpriteAnimation
#define _Included_com_github_sviengine_animation_SVISpriteAnimation
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_github_sviengine_animation_SVISpriteAnimation
 * Method:    nativeCreateSVISpriteAnimation
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_github_sviengine_animation_SVISpriteAnimation_nativeCreateSVISpriteAnimation
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);


/*
 * Class:     com_github_sviengine_animation_SVISpriteAnimation
 * Method:    nativeSetIntervalSVISpriteAnimation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVISpriteAnimation_nativeSetIntervalSVISpriteAnimation
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

