/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_animation_SVIParticleAnimation */

#ifndef _Included_com_github_sviengine_animation_SVIParticleAnimation
#define _Included_com_github_sviengine_animation_SVIParticleAnimation
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIParticleAnimation_nativeSetParticleEffect
  (JNIEnv *, jclass, jint, jint);


JNIEXPORT void JNICALL Java_com_github_sviengine_animation_SVIParticleAnimation_nativeSetKeyFrameParticleEffect
  (JNIEnv *, jclass, jint, jint);


JNIEXPORT jint JNICALL Java_com_github_sviengine_animation_SVIParticleAnimation_nativeCreateSVIParticleAnimation
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif

