/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_particle_SVIParticleEffect */

#ifndef _Included_com_github_sviengine_particle_SVIParticleEffect
#define _Included_com_github_sviengine_particle_SVIParticleEffect
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeCreateParticleEffect
  (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeAddParticles
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeSetDuration
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeSetPosition
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeSetScale
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeSetColor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeSetScaleKeyFrameAnimationProperty
  (JNIEnv *, jclass, jint, jint, jint, jint);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeSetColorKeyFrameAnimationProperty
  (JNIEnv *, jclass, jint, jint, jint, jint);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeSetPositionKeyFrameAnimationProperty
  (JNIEnv *, jclass, jint, jint, jint, jint);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeAddScaleKeyFrame
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeAddColorKeyFrame
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticleEffect_nativeAddPositionKeyFrame
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif

