/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_particle_SVIParticles */

#ifndef _Included_com_github_sviengine_particle_SVIParticles
#define _Included_com_github_sviengine_particle_SVIParticles
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeCreateParticles
  (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetTextureFile
  (JNIEnv *, jclass, jint, jstring, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetParticleCount
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetMaxDuration
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetRandomDuration
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetMaxSize
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetRandomSize
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetDefaultPosition
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetRandomPosition
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetMaxColor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetRandomColor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetDefaultGravity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetRandomGravity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetDefaultForce
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetRandomForce
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetMaxMass
  (JNIEnv *, jclass, jint, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetRandomMass
  (JNIEnv *, jclass, jint, jfloat);

JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetScaleKeyFrameAnimationProperty
  (JNIEnv *, jclass, jint, jint, jint, jint);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetColorKeyFrameAnimationProperty
  (JNIEnv *, jclass, jint, jint, jint, jint);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeSetPositionKeyFrameAnimationProperty
  (JNIEnv *, jclass, jint, jint, jint, jint);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeAddScaleKeyFrame
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeAddColorKeyFrame
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat);
	
JNIEXPORT void JNICALL Java_com_github_sviengine_particle_SVIParticles_nativeAddPositionKeyFrame
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);


#ifdef __cplusplus
}
#endif
#endif

