/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sviengine_scene_SVISceneNode */

#ifndef _Included_com_github_sviengine_scene_SVISceneNode
#define _Included_com_github_sviengine_scene_SVISceneNode
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL Java_com_github_sviengine_scene_SVISceneNode_nativeLoad3dModelFile
  (JNIEnv *, jclass, jint,  jstring);

#ifdef __cplusplus
}
#endif
#endif
